### ISSUE TITLE
on Android, there is no animation

### ISSUE THREAD

**Issue by souhaiebtar** [WrathChaos/react-native-dynamic-search-bar#1]
like in the picture below

![Imgur](https://i.imgur.com/70DX2Cs.gif)

for the icons, i edited `android/app/build.gradle` by adding in the end:
`apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`
but still there is no animation,

when running inside expo, we need to install `react-native-iphone-x-helper` or it will not work.

**Comment by WrathChaos** [comment]
Hello @souhaiebtar,
Thank you for the feedback, I think you fixed some of your issues :) 
To be honest, I have not tried animations on Android. Let me try them ASAP. 
Going to rewrite soon.

**Comment by WrathChaos** [comment]
Hello again @souhaiebtar ,
I've found and fixed the issues about icon problem and animations on the Android. These issues are not related to this library but here is how to do it :
### [Known Issue](https://github.com/WrathChaos/react-native-dynamic-search-bar#known-issues)
Also we finally got the new release 
### [Version Release: 0.1.1](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/0.1.1)

## Solutions

### Icon Solution
You need to add this line of code into app/gradle

> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle" 

### Animation Solution
Simply, you need to enable the experimental LayoutAnimation for the Android. 

> import {UIManager} from 'react-native';
> 
> constructor() {
>     super();
> 
>     if (Platform.OS === 'android') {
>       UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
>     }
> }

**Comment by WrathChaos** [comment]
@souhaiebtar The library is now completely Expo compatible. Please check the doc:
[Expo Compatibility](https://github.com/WrathChaos/react-native-dynamic-search-bar#expo-compatibility)
