### ISSUE TITLE
How do you style the actual searchBar, I want to increase the height of the search bar. I don't see a prop like containerStyle 

### ISSUE THREAD

**Issue by SiyabongaNzulwana** [WrathChaos/react-native-dynamic-search-bar#12]
Please help

**Comment by WrathChaos** [comment]
Hello, you can use "height" component for that. Have you tried it?

**Comment by SiyabongaNzulwana** [comment]
> Hello, you can use "height" component for that. Have you tried it?

Height component ??? what do you mean?

**Comment by SiyabongaNzulwana** [comment]
@WrathChaos Ok I think I got what you meant, thanks It works just fine, the thing is I didn't know that we could do that, i am used to create a style object then reference that object. I didn't know you can put a style property directly on the searchBar. Thanks again

**Comment by WrathChaos** [comment]
@SiyabongaNzulwana Love to hear that you made it happen :) If you have any other question, please feel free to ask and open an issue :)

Have fun

**Comment by surbhitrao** [comment]
Is there a way to change the width of the container of the entire search bar ?

**Comment by WrathChaos** [comment]
You can use `width` prop to change the whole search bar's width. I will update the documentation. Some of the props are missing.

**Comment by surbhitrao** [comment]
Yes it's working. Thanks :)
