### ISSUE TITLE
Another Problem, is it possible to move the searchBar, I would like to put the searchBar inside a View. If I position it absolute, and use top property, it does nothing.

### ISSUE THREAD

**Issue by SiyabongaNzulwana** [WrathChaos/react-native-dynamic-search-bar#13]

**Comment by WrathChaos** [comment]
Hello again @showcasecode, Can you show me what you're trying to do? If you wrap the SearchBar with <View> and set the position absolute, it should work. If it is not, I need to try.

**Comment by SiyabongaNzulwana** [comment]
`<View style={{backgroundColor: '#f7f7f7', padding: 10}}>
        <SearchBar
          height={60}
          fontColor="#9a9a9a"
          fontSize={18}
          iconColor="#c6c6c6"
          borderRadius={5}
          cancelIconColor="#777777"
          backgroundColor="#FFF"
          placeholder="Search Car Make"
          onChangeText={text => {
            this.onChangeText(text)
          }}
          onPressCancel={() => {
            this.filterList("");
          }}
          onPress={() =>{}}
        />`

I ideally I want to center the search bar inside this rectangular View . basically the View has a padding and the searchBar should appear nicely inside that View.

**Comment by WrathChaos** [comment]
You can use `shadowStyle` to handle the whole shadow style. I will test it with your example ASAP.

**Comment by WrathChaos** [comment]
Hey @SiyabongaNzulwana, I've tested with a View wrapper and it works. However, use 

```
alignItems: "center",
justifyContent: "center"
```

to center the SearchBar into the View Wrapper.

**Comment by JimTeva** [comment]
> You can use `shadowStyle` to handle the whole shadow style. I will test it with your example ASAP.

Could you help by giving us the props of shadowStyle to play with? Thanks!

**Comment by WrathChaos** [comment]
@JimTeva I'm glad that you're using this library :) If you have any idea to improve this library, I'm open for it :)

Have fun!

**Comment by JimTeva** [comment]
@WrathChaos I badly needed to separate cancel and clear in iOS so I switch to react-native-elements SearchBar component. So maybe add a separate cancel button for iOS for your library? Thank you!

**Comment by WrathChaos** [comment]
@JimTeva Actually you can use anything for cancel button with this prop: `cancelComponent`. Does not it help for you? I literally could not exactly get the `separate cancel and clear in iOS` logic? What exactly do you need? Also, let's open another issue for this discussion?
