### ISSUE TITLE
[Android] Error while updating property 'backgroundColor' in shadow node of type: AndroidTextInpout

### ISSUE THREAD

**Issue by abhishekdewan101** [WrathChaos/react-native-dynamic-search-bar#15]
So while using the search bar in a project of mine I ran into a peculiar issue. If I use the search bar in the following way 

`<SearchBar
          fontColor="#aa8dcc"
          iconColor="#d7bdf5"
          cancelIconColor="#d7bdf5"
          backgroundColor="#f9f9f9"
          placeholder="Search here"
          onChangeText={this.onChangeText}
          onPressCancel={() => {
            this.setState({ isSearching: false });
          }}
          onPressToFocus={true}
          onSubmitEditing={this.onSubmit}
          noExtraMargin={true}
        />`

that causes the application to be broken on android while iOS works properly. However removing the background color property all together fixes the issue. I am not sure if I am setting the background color in a weird way or is there something I should be doing to differently.

![image](https://user-images.githubusercontent.com/2817833/71539633-1785d700-28f4-11ea-9dad-de97a071461a.png)

**Comment by abhishekdewan101** [comment]
Did some more digging and it turns out that the Advanced Usage example on the Readme needed to be updated to remove the usage of backgroundColor. Here's the PR https://github.com/WrathChaos/react-native-dynamic-search-bar/pull/16

**Comment by WrathChaos** [comment]
Working on it :) Let me test the backgroundColor issue

**Comment by WrathChaos** [comment]
@abhishekdewan101 It works completely fine with the library's example. Please be sure that you're working with the latest version (currently: 0.3.1) and please try your code with library's example first :)
