### ISSUE TITLE
Expo install method is not working

### ISSUE THREAD

**Issue by andordavoti** [WrathChaos/react-native-dynamic-search-bar#18]
I tried installing with expo, but got this message:

`npm i WrathChaos/react-native-dynamic-search-bar#expo
npm ERR! code 1
npm ERR! Command failed: git checkout expo
npm ERR! error: pathspec 'expo' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andordavoti/.npm/_logs/2020-02-13T18_40_43_567Z-debug.log`

**Comment by WrathChaos** [comment]
Hello, I will fix it ASAP and will inform you :)

**Comment by andordavoti** [comment]
thanks! somehow got it working anyways from another guide or something

**Comment by WrathChaos** [comment]
@andordavoti Can you post what was wrong? so everyone can find and fix easily

**Comment by surbhitrao** [comment]
`npm i WrathChaos/react-native-dynamic-search-bar#expo`
is still not working.
How I got it installed in Expo was I copied all the dependencies from the example folder's package.json and then run yarn install once.

`"@freakycoder/react-native-helpers": "^0.1.0",
    "react-native-dynamic-search-bar": "0.3.1",
    "react-native-fast-image": "^7.0.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-ripple": "^0.9.1"
     "react-native-svg": "9.13.3",
    "react-native-svg-charts": "^5.3.0",
     "react-native-gradient-card-view": "WrathChaos/react-native-gradient-card-view#expo",
    "react-native-dynamic-vector-icons": "WrathChaos/react-native-dynamic-vector-icons#expo",
`

**Comment by WrathChaos** [comment]
@surbhitrao You need to install 
`npm i WrathChaos/react-native-dynamic-search-bar#expo`

This library's **expo version**, not default version.

**Comment by surbhitrao** [comment]
I'm getting this error `error An unexpected error occurred: "could not find a copy of react-native to link in D:\\React Native\\CRM_RN-master\\node_modules\\react-native-dynamic-search-bar\\node_modules".`

**Comment by WrathChaos** [comment]
@surbhitrao, Are you using Expo?

**Comment by surbhitrao** [comment]
Yes

**Comment by WrathChaos** [comment]
Can you try it with latest version? also please use this branch not default one.
`npm i WrathChaos/react-native-dynamic-search-bar#expo`
