### ISSUE TITLE
Module not found: Can't resolve '@expo/vector-icons/Fontisto' 

### ISSUE THREAD

**Issue by lexaguilar** [WrathChaos/react-native-dynamic-search-bar#19]
C:/Users/Lex Aguilar/Documents/React Native/test/node_modules/react-native-dynamic-vector-icons/lib/components/Icon.tsx
Module not found: Can't resolve '@expo/vector-icons/Fontisto' in 'C:\Users\Lex Aguilar\Documents\React Native\test\node_modules\react-native-dynamic-vector-icons\lib\components'

package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@egjs/hammerjs": "^2.0.17",
    "@expo/vector-icons": "^10.0.6",
    "@freakycoder/react-native-helpers": "^0.1.2",
    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-dynamic-search-bar": "^0.3.1",
    "react-native-dynamic-vector-icons": "^0.2.2",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7"
    
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.1"
  },
  "private": true
}

**Comment by WrathChaos** [comment]
Hello @lexaguilar,
Here is the original expo issue: https://github.com/expo/vector-icons/issues/112
You can follow up on the issue here. Unfortunately, this is an expo issue, I could not fix it. It works great without expo tho.
