### ISSUE TITLE
The input data source to be dynamic `onChangeText` i.e. while typing 

### ISSUE THREAD

**Issue by ansari-haseb** [WrathChaos/react-native-dynamic-search-bar#21]
The feature to change the complete source data depending on the `searchText`. So, the input data to be fed to the component will be a result from the elasticsearch data which will change everytime depending on the searchText. In my usecase, the list is very long and I don't want the complete list to be transfered over the network.

**Comment by tiagostutz** [comment]
I think this would be more a backend concern than frontend. 
You can put some logic in the `onChangeText` method to it fire the backend just after some text length or time (with a `setTimeout`) and you could make your backend return just the top N relevant results to be presented in the list. 

So I don't think there is something to be implemented here, in the component.
Did I miss something about the issue?

**Comment by WrathChaos** [comment]
You need to make this logic outside of this component. The component itself just returns the user input and you need to use this input for elastic search or whatever you need.
