### ISSUE TITLE
Missing backgroundColor and fontFamily from configuration props

### ISSUE THREAD

**Issue by whenmoon** [WrathChaos/react-native-dynamic-search-bar#22]
This works:
```
backgroundColor={COL_DARK_HIGHLIGHT}
fontFamily="ProximaNova-Regular"
```
But is not documented in the configuration props :)

**Comment by WrathChaos** [comment]
Hello @whenmoon,
Thank you so much for the reminder :) I'm going to add them on README :) 
Also, thank you for using this library. If you have an idea to improve this library, please let me know :)

**Comment by whenmoon** [comment]
It's a great library!! Sorry - I would of made a PR myself but I was short on time today. Thanks!

**Comment by WrathChaos** [comment]
Gonna update it today :)

**Comment by WrathChaos** [comment]
Updated, thakn you @whenmoon :)
