### ISSUE TITLE
shadowStyle prop is not passed through

### ISSUE THREAD

**Issue by swparkaust** [WrathChaos/react-native-dynamic-search-bar#26]
I am trying to remove the shadow that Android gives around the search bar, so I passed `shadowStyle={{ elevation: 0 }}` into the component.
However, the `shadowStyle` prop doesn't seem to have any effect, as opposed to what is stated in the readme.
I have looked at the source, and it seems like you are just reading `_shadowStyle` from the style file, where it sets the `elevation` to `5`. 
Presumably, it needs to pass through `props.shadowStyle` as well, so I can override the default style?

**Comment by WrathChaos** [comment]
Hey again @swparkaust,
Thank you for the issue :) While refactoring with Typescript, I guess I missed the shadowStyle prop :(

I've put it back with the new version. Can you try to delete and re-install the expo version? 

Also the new version is here for pure react native: 
## [Release 1.0.2](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/1.0.2)

**Comment by swparkaust** [comment]
@WrathChaos It works now. 👍
