### ISSUE TITLE
Documentation: Missing Props

### ISSUE THREAD

**Issue by WrathChaos** [WrathChaos/react-native-dynamic-search-bar#27]
Missing Props
* height
* width
etc...

**Comment by tiagostutz** [comment]
Hi @WrathChaos I'd like to contribute with this issue but I couldn't find any CONTRIBUTING docs. Are this contributing docs in progress? Or maybe you need some help with this also? I can help with that too.

What you say?

**Comment by WrathChaos** [comment]
I don't have a contribution doc because rarely people contribute :) I would love you to help. Let's talk about it sometime

**Comment by tiagostutz** [comment]
OK!

Do you want me to take this issue here?

**Comment by surbhitrao** [comment]
I'd love to contribute as well.

**Comment by WrathChaos** [comment]
Hey guys really sorry for the late response. I was sick :( 
You can take the issue here, I can edit/change and give you feedback about that. @tiagostutz 
I would love to take your contribution @surbhitrao :)

**Comment by tiagostutz** [comment]
@WrathChaos sorry about that! Hope your are doing better now! =)

@surbhitrao do you like to take this issue here? If so, I can pass it to you as I have already made one PR. If not, I will keep for me this issue and will make the PR.

**Comment by surbhitrao** [comment]
Sure, we can take the issue here.

**Comment by WrathChaos** [comment]
Hey @surbhitrao, 
What is going on with this issue? Will you solve it?

**Comment by tiagostutz** [comment]
If @surbhitrao does not respond, I can take this.
Just let me know, @WrathChaos

**Comment by WrathChaos** [comment]
@tiagostutz, yes please :) 
I am open for any PR and any idea :)

**Comment by tiagostutz** [comment]
Nice!
I'm searching here for some doc generator and I'm making some testes with https://github.com/reactjs/react-docgen and https://github.com/TypeStrong/typedoc. I don't have experience with "professional" documentation, so if you have any preference, let me know.

**Comment by WrathChaos** [comment]
Hey @tiagostutz,
Actually we do not need a doc generator. The best professional documentation is a manual one :)

**Comment by tiagostutz** [comment]
So, let's go manual! =)

**Comment by tiagostutz** [comment]
Can I put the properties in alphabetical order? Or you want to keep the order as it is and I should put the new properties at the end of the table?
