### ISSUE TITLE
Add instructions on how to run the Example

### ISSUE THREAD

**Issue by tiagostutz** [WrathChaos/react-native-dynamic-search-bar#28]
Hi, I just forked the project and I was attempting to run the example, but I had some struggling. Part of it is because of my env here, but, anyway, I'm writing a README here for future contributors that can have the same problems to know how to overcome them.

I just wrote the iOS part and now I'm going to write the Android one.

If you could assign this issue to me I'd appreciate.

Thanks!

**Comment by WrathChaos** [comment]
@tiagostutz, I've invited you to the repo :) Please accept it.

**Comment by tiagostutz** [comment]
Done! =)
