### ISSUE TITLE
Just Doesn't Work And Contains NODE_MODULES

### ISSUE THREAD

**Issue by stephanoparaskeva** [WrathChaos/react-native-dynamic-search-bar#32]
This lib has so many dependencies so i'm not sure where the error comes from.
Version: RN 0.62.2 (Non-Expo)
Everything at @latest
<img width="371" alt="Screenshot 2020-06-21 at 22 39 32" src="https://user-images.githubusercontent.com/40718272/85235838-38953380-b410-11ea-975a-81187fc2bab9.png">

**Comment by WrathChaos** [comment]
Hello @stephanoparaskeva, 
Can you try it on 0.61.5? Also have you ever tested it on a fresh example on 62.2?

**Comment by stephanoparaskeva** [comment]
> Hello @stephanoparaskeva,
> Can you try it on 0.61.5? Also have you ever tested it on a fresh example on 62.2?

I think this is the issue 
<img width="297" alt="Screenshot 2020-06-21 at 22 44 45" src="https://user-images.githubusercontent.com/40718272/85235905-d8eb5800-b410-11ea-8e51-6c250b2463aa.png">

Thanks for the quick response btw, really would like to use your work

**Comment by WrathChaos** [comment]
I think I have never tested it on 0.62.2. It totally works on 0.61.5 as you can tested on example. I will test it on 0.62.2 now, while I'm doing that can you run this command and test it please: 

`watchman watch-del-all && rm -rf node_modules/ && npm cache clean -f && npm install && react-native run-ios `

**Comment by stephanoparaskeva** [comment]
> I think I have never tested it on 0.62.2. It totally works on 0.61.5 as you can tested on example. I will test it on 0.62.2 now, while I'm doing that can you run this command and test it please:
> 
> `watchman watch-del-all && rm -rf node_modules/ && npm cache clean -f && npm install && react-native run-ios `

I've run that command already, I've fixed the issue now but as I'm saying:

The issue is that you are exporting Node_modules in your build. The package is installed and contains node_modules, which it should not.

**Comment by WrathChaos** [comment]
@stephanoparaskeva You're right :) I forgot the dependency part into the library. Thank you to awake of that. 

Can you please check this version:
## [1.2.1](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/1.2.1)

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva You're right :) I forgot the dependency part into the library. Thank you to awake of that.
> 
> Can you please check this version:
> 
> ## [1.2.1](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/1.2.1)

Awesome this works great with RN 0.62.2
