### ISSUE TITLE
Unable to change Placeholder text color.

### ISSUE THREAD

**Issue by VR-123** [WrathChaos/react-native-dynamic-search-bar#51]
How to change placeholder text color

**Comment by WrathChaos** [comment]
Hello @VR-123,
I've added the `placeholderTextColor` customization prop option :) You can use it for that. 
Have fun!


## [Version 2.0.1](https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/2.0.1)

**Comment by VR-123** [comment]
Thanks 👍 👍
