### ISSUE TITLE
react-native-iphone-x-helper module not found

### ISSUE THREAD

**Issue by dmongit** [WrathChaos/react-native-dynamic-search-bar#8]
I get an error that the `react-native-iphone-x-helper` module can't be found.

I run `C:\folder\app\android> ./gradlew assembleRelease`

I get this error: `error Unable to resolve module `react-native-iphone-x-helper` from `node_modules\react-native-dynamic-search-bar\lib\src\SearchBar.style.js`: react-native-iphone-x-helper could not be found within the project.`

Thanks (again)!

**Comment by WrathChaos** [comment]
Hello @dmongit 
Did you install the library?
`npm i react-native-iphone-x-helper`

**Comment by dmongit** [comment]
@WrathChaos I'd imagine that'd work, but it's inside of your package. My temp fix was to remove the import of `react-native-iphone-x-helper` from within my instance of your package in `node_modules\react-native-dynamic-search-bar\lib\src\SearchBar.style.js`

**Comment by dmongit** [comment]
I installed `react-native-iphone-x-helper` in my project, and that solved the problem up the chain. I think I also missed a module because your dependencies have dependency requirements. This one was on me, though, I think your read me could include that `react-native-iphone-x-helper` is a required dependency. Thanks!

**Comment by WrathChaos** [comment]
@dmongit Loved to hear that you've solved your problem :) I always try to use less dependent libraries, however sometimes these helpers really awesome and time-saving.

**Comment by ciruz** [comment]
Hey @WrathChaos the module **react-native-iphone-x-helper** is somehow still missing in your dependencies. I know I can install it by hand, but this is no real fix.

**Comment by WrathChaos** [comment]
@ciruz Thank you to remind me. I'm going to remove that dependency with the new release. I will inform you for new release.

**Comment by WrathChaos** [comment]
@ciruz and @dmongit I've released the new version: **_[0.3.0]_**(https://github.com/WrathChaos/react-native-dynamic-search-bar/releases/tag/0.3.0) please give it a try. There is also an updated with latest versions example.
